version: '3'

services:

    scala-api:
        build:
            context: .
            dockerfile: scala-api/Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - './scala-api:/scala-api'

        command: >
            sh -c 'sbt run'

        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_PASS=supersecretpassword
            - DB_USER=postgres
            - SECRET_KEY=foo
            - DEBUG=1
            - DB_PORT=5432
            - CLIENT_ID=716374017659-76kpha4mqm82083hj8krgea83e2d03oo.apps.googleusercontent.com
            - ENV=DEVELOPMENT
            - PORT=8080
        depends_on:
            - db

    db:
        image: postgres:10-alpine
        ports:
            - '5432:5432'
        volumes:
          - postgres_data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=app
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=supersecretpassword


volumes:
  postgres_data:
